class_name TypeUtils
extends Reference


"CLASS CONSTANTS"
const TYPE_STRINGS: Dictionary = {
	TYPE_NIL: "TYPE_NIL",
	TYPE_BOOL: "TYPE_BOOL",
	TYPE_INT: "TYPE_INT",
	TYPE_REAL: "TYPE_REAL",
	TYPE_STRING: "TYPE_STRING",
	TYPE_VECTOR2: "TYPE_VECTOR2",
	TYPE_RECT2: "TYPE_RECT2",
	TYPE_VECTOR3: "TYPE_VECTOR3",
	TYPE_TRANSFORM2D: "TYPE_TRANSFORM2D",
	TYPE_PLANE: "TYPE_PLANE",
	TYPE_QUAT: "TYPE_QUAT",
	TYPE_AABB: "TYPE_AABB",
	TYPE_BASIS: "TYPE_BASIS",
	TYPE_TRANSFORM: "TYPE_TRANSFORM",
	TYPE_COLOR: "TYPE_COLOR",
	TYPE_NODE_PATH: "TYPE_NODE_PATH",
	TYPE_RID: "TYPE_RID",
	TYPE_OBJECT: "TYPE_OBJECT",
	TYPE_DICTIONARY: "TYPE_DICTIONARY",
	TYPE_ARRAY: "TYPE_ARRAY",
	TYPE_RAW_ARRAY: "TYPE_RAW_ARRAY",
	TYPE_INT_ARRAY: "TYPE_INT_ARRAY",
	TYPE_REAL_ARRAY: "TYPE_REAL_ARRAY",
	TYPE_STRING_ARRAY: "TYPE_STRING_ARRAY",
	TYPE_VECTOR2_ARRAY: "TYPE_VECTOR2_ARRAY",
	TYPE_VECTOR3_ARRAY: "TYPE_VECTOR3_ARRAY",
	TYPE_COLOR_ARRAY: "TYPE_COLOR_ARRAY",
	TYPE_MAX: "TYPE_MAX",
}


"CLASS STATIC METHODS"
static func get_type_string(type: int) -> String:
	return TYPE_STRINGS.get(type, "UNKNOWN")
